using System;

namespace P12_Highly_divisible_triangular_number
{
    class Program
    {
        static void Main(string[] args)
        {
            //Highly divisible triangular number (Problem 12)
            //https://projecteuler.net/problem=12

            //The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.The first ten terms would be:
            //1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
            //Let us list the factors of the first seven triangle numbers:

            //We can see that 28 is the first triangle number to have over five divisors.
            //What is the value of the first triangle number to have over five hundred divisors ? 

            long num = 0;
            for (int i = 1; ; i++)
            {
                num += i;
                int count = 1;
                for (int div = 1; div<(int)num/2 ; div++)
                {
                    if (num%div == 0)
                    {
                        count++;
                    }
                }
                Console.WriteLine($" {num}, {count}");

                if (count >= 500)
                {
                    Console.WriteLine($"\n {num}, {count}");
                    break;
                }
            }

            //Time EXCEEDED. too slow bitch (took 10 mins)
            //result 76576500 (coorect) 5/06/22
        }
    }
}
